### ISSUE TITLE
MissingPluginException when using `flutter test`

### ISSUE THREAD

**Issue by stephane-archer** [authpass/macos_secure_bookmarks#12]
MissingPluginException when using `flutter test`
```
    return await _secureBookmarks.bookmark(fileSystemEntity);
```
```
MissingPluginException (MissingPluginException(No implementation found for method bookmarkData on channel codeux.design/macos_secure_bookmarks))
```

**Comment by hpoul** [comment]
Hi,
I don't think it makes much sense to support unit tests by the plugin.. (without initializing the actual plugin) see https://docs.flutter.dev/testing/plugins-in-tests for some workarounds.. Either just wrap the plugin altogether or mock the channel using https://api.flutter.dev/flutter/flutter_test/TestDefaultBinaryMessenger-class.html

**Comment by stephane-archer** [comment]
Hi @hpoul, I'm not sure I understand why the test environment doesn't initialise the plugin, is there a way to make it behave normally using Flutter test? How can I test code that use your plugin without mocking? (I'm new to testing using dart/flutter)
